"""Assembling a loadable extension directory from what the wheel carries.

THE DRIFT PROBLEM, which is the reason this module exists rather than a
prebuilt .xpi sitting in the package.

`projection.bundle.js` is 300 KB of GENERATED code compiled by `bundle.py`
from `projection/*.js`. Every other lane runs those sources directly. Lane C
runs the compiled copy. `test_ext_bundle.py` pins the copy in the repository
equal to what the module generates, so a projection edit that is not rebuilt
fails the suite instead of shipping a Lane C that reads pages differently
from every other lane.

That test protects the repository. It does not protect an INSTALL. Ship a
prebuilt extension inside the wheel and the pin is a claim about the machine
that built it, checked by nobody afterwards: a user with a patched projection,
a partial upgrade, or a wheel assembled from a dirty tree gets a browser
reading pages by rules the server no longer holds, and no test runs in the
field to notice. Phases 2 and 3 both recommended closing this the same way,
and this is the close.

So the wheel carries SOURCES, and `--setup-browser` compiles the bundle from
the installed `projection/*.js` at the moment it stages the directory. The
staged bundle is then correct by construction for that install, rather than
correct by history for some build machine. `MANIFEST` records what was
written and from where, so a support question has an answer.

The repository's own `extension/` directory is the Firefox staging output,
generated by this module and pinned by a drift test the same way the bundle
is. It is what the live tests load, so the thing under test and the thing
shipped come off one press.

    Rebuild:  python -m kitchensink4web.extension.artifact
"""

from __future__ import annotations

import hashlib
import shutil
from pathlib import Path

from . import bundle, manifests

#: The compiled projection, staged under this name in every flavor.
BUNDLE_NAME = "projection.bundle.js"

#: Files copied verbatim out of `assets/`, per flavor. `compat.js` is listed
#: for chromium because its content script needs it as a separate file; the
#: BACKGROUND copy is concatenated instead (see `_background`).
_VERBATIM = {
    "firefox": ("content.js",),
    "chromium": ("content.js", "compat.js"),
}


def assets_dir() -> Path:
    """Where the wheel keeps the extension's JavaScript."""
    return Path(__file__).resolve().parent / "assets"


def _read_asset(name: str) -> str:
    return (assets_dir() / name).read_text(encoding="utf-8")


def _background(flavor: str) -> str:
    """The background script for a flavor.

    Firefox gets the file untouched, which is the point: the build that three
    phases of live testing were run against is the build that ships.

    Chromium gets the shim welded on the front. MV3 allows exactly one
    ``service_worker`` file and importing a second would make the whole thing
    an ES module, which changes how `background.js` is parsed. Concatenation
    changes nothing about how it is parsed and puts `browser` in scope before
    the first line that reads it.
    """
    body = _read_asset("background.js")
    if flavor == "firefox":
        return body
    shim = _read_asset("compat.js")
    return (
        shim
        + "\n/* ---- the shared background script, verbatim from"
          " assets/background.js ---- */\n\n"
        + body
    )


def files(flavor: str, *, key: str | None = None) -> dict[str, str]:
    """Every file of a staged extension, as name -> text.

    Returned rather than written so a test can compare a staging directory
    against this without a filesystem round trip, and so the manifest, the
    bundle and the scripts all come from one description.
    """
    if flavor not in manifests.FLAVORS:
        raise ValueError(
            f"unknown extension flavor {flavor!r}; expected one of {manifests.FLAVORS}"
        )
    out = {
        "manifest.json": manifests.render(flavor, key=key),
        "background.js": _background(flavor),
        # Compiled HERE, from the projection sources this install has, which
        # is the whole argument of the module docstring.
        BUNDLE_NAME: bundle.build(),
    }
    for name in _VERBATIM[flavor]:
        out[name] = _read_asset(name)
    return out


def digest(flavor: str, *, key: str | None = None) -> str:
    """A short fingerprint of a staged extension.

    Two installs that stage the same bytes get the same string. It is what
    makes "is the extension in my browser the one this server compiled?" a
    question with an answer, and it is printed by ``--setup-browser`` for
    that reason.
    """
    h = hashlib.sha256()
    for name, text in sorted(files(flavor, key=key).items()):
        h.update(name.encode("utf-8"))
        h.update(b"\0")
        h.update(text.encode("utf-8"))
        h.update(b"\0")
    return h.hexdigest()[:16]


def stage(dest: Path, flavor: str = "firefox", *, key: str | None = None,
          clean: bool = True) -> dict:
    """Write a loadable extension directory and report what landed.

    ``clean`` removes files the previous staging left and this one does not
    produce. A stale `background.js` from a flavor switch is not a cosmetic
    problem: Chromium would load a Firefox background script, find no
    `browser` global, and fail at the first line with an error naming
    nothing useful.
    """
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    written = files(flavor, key=key)

    if clean:
        for existing in dest.iterdir():
            if existing.is_file() and existing.name not in written:
                existing.unlink()
            elif existing.is_dir():
                shutil.rmtree(existing)

    for name, text in written.items():
        # newline="\n" so the bundle's drift pin does not depend on which
        # platform staged it.
        (dest / name).write_text(text, encoding="utf-8", newline="\n")

    return {
        "flavor": flavor,
        "path": str(dest),
        "files": sorted(written),
        "bytes": {name: len(text.encode("utf-8")) for name, text in written.items()},
        "digest": digest(flavor, key=key),
        "extension_id": (manifests.GECKO_ID if flavor == "firefox"
                         else unpacked_chromium_id(dest) if key is None else None),
        "version": manifests.VERSION,
    }


def unpacked_chromium_id(path: Path) -> str:
    """The id Chromium assigns an unpacked extension loaded from ``path``.

    Chromium hashes the absolute directory path, takes the first sixteen
    bytes, and maps each hex nibble onto ``a``..``p``. It is deterministic,
    which is the only reason a native messaging host manifest can name the id
    of an extension that was never packed: `allowed_origins` has to carry an
    exact ``chrome-extension://<id>/`` and there is no id to read until the
    browser has already loaded the thing.

    MEASURED against a real Chromium rather than assumed; the phase 4 report
    records the comparison and what it cost when the answer disagreed.
    """
    raw = str(Path(path).resolve())
    # Chromium hashes the path bytes as the platform gives them. On Windows
    # the path is UTF-16LE inside the browser; elsewhere it is the raw
    # filesystem bytes.
    import os as _os
    if _os.name == "nt":
        encoded = raw.encode("utf-16-le")
    else:
        encoded = raw.encode("utf-8")
    hexed = hashlib.sha256(encoded).hexdigest()[:32]
    return "".join(chr(ord("a") + int(ch, 16)) for ch in hexed)


def repo_extension_dir(root: Path | None = None) -> Path:
    """The repository's staged Firefox build, which the live tests load."""
    here = Path(__file__).resolve()
    base = root if root is not None else here.parents[3]
    return Path(base) / "extension"


def main() -> int:  # pragma: no cover - a developer convenience
    result = stage(repo_extension_dir(), "firefox")
    total = sum(result["bytes"].values())
    print(f"staged {result['flavor']} into {result['path']} "
          f"({len(result['files'])} files, {total} bytes, "
          f"digest {result['digest']})")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
