"""Load every corpus B page and report what the browser actually found.

A fixture corpus rots quietly. A vendored UMD build gets moved, a script
throws on line one and the page still returns 200, a generated file goes
stale against its generator, and the page keeps "passing" because nothing
ever asserted that it loads. This script is the assertion: it serves
`corpus/b/` over localhost with the bundled Chromium, opens every page, and
prints the node count, the control count, and every console error and page
error raised during load.

It also writes `MANIFEST.json` when run with `--manifest`, so the node counts
in the manifest are MEASURED rather than estimated. The landmine mapping is
hand-written and lives in this file, because a landmine is a claim about
intent and no script can infer one.

Exit code 0 means every page loaded with no page error. Console errors are
reported but do not fail the run: `console_flood.html` emits two on purpose
and the cross-origin iframes fail to load offline by design.

Run:  .venv/Scripts/python.exe -X utf8 corpus/b/_check.py
      .venv/Scripts/python.exe -X utf8 corpus/b/_check.py --manifest
"""

from __future__ import annotations

import asyncio
import functools
import hashlib
import http.server
import json
import socketserver
import subprocess
import sys
import threading
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(ROOT / "src"))

from kitchensink4web.engine.session import MANAGER  # noqa: E402

#: file -> (what it is, the landmines PLAN 1.3 names that it carries).
#: This is the corpus B index: every landmine PLAN 1.3 names, plus the two
#: the Phase 2 gate adds. `--manifest` inverts it into `landmine_index`, so
#: the mapping is written once and read both ways.
PAGES: dict[str, tuple[str, list[str]]] = {
    "dom50k.html": (
        "50,000 elements of ordinary document, generated by _generate.py "
        "and committed",
        ["50,000-node DOM"]),
    "infinite.html": (
        "a feed that appends 25 more items every time the sentinel is seen",
        ["infinite-scroll list"]),
    "virtual.html": (
        "a real react-window FixedSizeList rendering 20 of 5,000 rows "
        "(copied from spikes/s2)",
        ["react-window virtualized list, 20 of 5,000 rows"]),
    "app.html": (
        "a React SPA: node-replacing remount, label change, list reorder, "
        "hash routing, duplicate control names, modal (copied from spikes/s2)",
        ["React re-render", "client-side route change",
         "duplicate control names in one region"]),
    "other.html": (
        "the cross-navigation look-alike for app.html (copied from spikes/s2)",
        ["cross-page rebind trap"]),
    "canvas.html": (
        "a 900x520 canvas painting a whole toolbar and chart, no text in "
        "the DOM",
        ["canvas-rendered UI over 80x80 with no text projection"]),
    "iframes.html": (
        "top document of the frame chain, plus a cross-origin frame at the "
        "top level",
        ["three levels of nested iframes", "cross-origin iframe"]),
    "iframe_l2.html": (
        "level 2 of the frame chain, same origin, carries its own controls",
        ["three levels of nested iframes"]),
    "iframe_l3.html": (
        "level 3 of the frame chain, and the cross-origin frame at the "
        "bottom of it",
        ["three levels of nested iframes", "cross-origin iframe"]),
    "shadow.html": (
        "two open shadow roots, three closed ones, one of them nested "
        "inside an open root",
        ["open shadow roots", "closed shadow roots"]),
    "cookiewall.html": (
        "a consent notice and a subscribe modal stacked over an ordinary "
        "article",
        ["cookie banner dominating the first read",
         "modal overlay dominating the first read"]),
    "mutating.html": (
        "text, labels, list order, and one whole button node replaced every "
        "100ms",
        ["page that mutates every 100ms"]),
    "tables.html": (
        "a rowspan/colspan table, a role=table of divs, a role=grid of "
        "divs, and a layout table",
        ["table with rowspan and colspan",
         "'table' rendered as nested divs with role=table/grid"]),
    "lazy.html": (
        "five lazy images across three placeholder techniques, plus two "
        "below a tall spacer",
        ["lazy images with placeholder src"]),
    "pathological.html": (
        "five ways a click reports success and does nothing",
        ["React control checking event.isTrusted",
         "<div onclick> invisible to role-based selectors",
         "element that moves under the cursor mid-animation",
         "overlay that intercepts clicks",
         "portal-rendered dropdown absent from the a11y tree"]),
    "console_flood.html": (
        "4,000 console lines before load, 40 more per second, two real "
        "errors buried in them",
        ["page emitting thousands of console lines"]),
    "secrets.html": (
        "a checkout form with populated password, one-time-code, and "
        "cc-number fields, plus a token field outside the form",
        ["form with type=password and cc-number fields"]),
    "loose_controls.html": (
        "an app shell with 19 controls outside any form and a 6-control "
        "form for contrast",
        ["loose controls outside any <form> (Phase 2 gate)"]),
    "bigform.html": (
        "320 fields in one form, submit button last, secrets past field 240",
        ["form with several hundred fields, for rung-5 capped inventory "
         "(Phase 2 gate)"]),
}

PROBE = """
(() => ({
  nodes: document.getElementsByTagName('*').length,
  title: document.title,
  controls: document.querySelectorAll(
    'input, select, textarea, button, [role=button], [role=switch]').length,
  links: document.querySelectorAll('a[href]').length,
  iframes: document.querySelectorAll('iframe').length,
  tables: document.querySelectorAll('table').length,
  role_tables: document.querySelectorAll('[role=table], [role=grid]').length,
  images: document.querySelectorAll('img').length,
  text_chars: (document.body ? (document.body.innerText || '') : '').length,
  truth: window.__truth || null,
}))()
"""


class _Quiet(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *args):  # noqa: D102, ANN002
        pass


def _serve(directory: Path) -> tuple[int, socketserver.TCPServer]:
    handler = functools.partial(_Quiet, directory=str(directory))
    httpd = socketserver.TCPServer(("127.0.0.1", 0), handler)
    threading.Thread(target=httpd.serve_forever, daemon=True).start()
    return httpd.server_address[1], httpd


def _kst() -> str:
    out = subprocess.run(["date", "+%Y-%m-%d %H:%M"], capture_output=True,
                         text=True, shell=False)
    return out.stdout.strip() if out.returncode == 0 else ""


async def _load(page, url: str) -> dict:
    errors: list[str] = []
    console: list[str] = []

    def on_console(msg):
        if msg.type == "error":
            console.append(msg.text[:160])

    def on_pageerror(exc):
        errors.append(str(exc)[:200])

    page.on("console", on_console)
    page.on("pageerror", on_pageerror)
    try:
        await page.goto(url, wait_until="load", timeout=90000)
        # Give React roots, shadow attachment, and the observers a turn.
        await page.wait_for_timeout(600)
        info = await page.evaluate(PROBE)
    finally:
        page.remove_listener("console", on_console)
        page.remove_listener("pageerror", on_pageerror)
    info["page_errors"] = errors
    # Cap the console list. console_flood.html would otherwise put its whole
    # flood in the report, which is the failure the page exists to provoke.
    info["console_errors"] = console[:5]
    info["console_error_count"] = len(console)
    return info


async def main() -> None:
    port, httpd = _serve(HERE)
    session = await MANAGER.open(lane="A", engine="chromium", headless=True)
    rows: dict[str, dict] = {}
    failed: list[str] = []
    try:
        record = session.page(session.focused)
        page = record.page
        for name in PAGES:
            if not (HERE / name).exists():
                print(f"{name:>22}: MISSING")
                failed.append(name)
                continue
            try:
                info = await _load(page, f"http://127.0.0.1:{port}/{name}")
            except Exception as exc:  # noqa: BLE001
                print(f"{name:>22}: LOAD FAILED {exc.__class__.__name__}")
                failed.append(name)
                continue
            rows[name] = info
            flag = ""
            if info["page_errors"]:
                flag = f"  PAGE ERROR: {info['page_errors'][0]}"
                failed.append(name)
            elif info["console_error_count"]:
                flag = f"  ({info['console_error_count']} console errors)"
            print(f"{name:>22}: {info['nodes']:>6} nodes, "
                  f"{info['controls']:>4} controls, "
                  f"{info['links']:>4} links, "
                  f"{info['iframes']} iframes{flag}")
    finally:
        await MANAGER.close(session.session_id)
        httpd.shutdown()

    if "--manifest" in sys.argv:
        manifest = {
            "corpus": "B",
            "purpose": "the pathological fixture site (PLAN 1.3): every "
                       "landmine, deliberately, served from the repo",
            "measured_kst": _kst(),
            "lane": "A(chromium) headless, served from 127.0.0.1",
            "network": "none required. The two https://example.com iframes "
                       "are expected to fail offline; the iframe ELEMENT is "
                       "the fixture, not its content.",
            "generated_files": {
                "dom50k.html": "corpus/b/_generate.py. The generator writes "
                               "the file and the FILE is committed, so the "
                               "node count is a property of the bytes on "
                               "disk rather than of how fast the machine "
                               "ran. No inline script builds nodes.",
                "bigform.html": "corpus/b/_generate.py, same reason: 320 "
                                "controls are not reviewable by hand and a "
                                "hand-maintained file that size drifts.",
            },
            "copied_from_spikes": {
                "app.html": "spikes/s2/fixtures/app.html",
                "other.html": "spikes/s2/fixtures/other.html",
                "virtual.html": "spikes/s2/fixtures/virtual.html",
                "vendor/": "spikes/s2/fixtures/vendor/ (React 18.3.1 and "
                           "react-window 1.8.10 as UMD builds, so there is "
                           "no build step and no network at run time)",
                "note": "COPIED, not moved. PLAN 1.3 says the S2 subset "
                        "moves into corpus B proper before Phase 2 closes; "
                        "spikes/s2 is left intact so the spike record still "
                        "runs.",
            },
            "pages": {},
        }
        for name, (what, mines) in PAGES.items():
            row = rows.get(name)
            path = HERE / name
            entry = {
                "what": what,
                "landmines": mines,
                "loaded": row is not None and not row["page_errors"],
            }
            if path.exists():
                data = path.read_bytes()
                entry["bytes"] = len(data)
                entry["sha256"] = hashlib.sha256(data).hexdigest()
            if row:
                entry.update({
                    "nodes": row["nodes"],
                    "title": row["title"],
                    "controls": row["controls"],
                    "links": row["links"],
                    "iframes": row["iframes"],
                    "tables": row["tables"],
                    "role_tables": row["role_tables"],
                    "images": row["images"],
                    "text_chars": row["text_chars"],
                    "page_errors": row["page_errors"],
                    "console_error_count": row["console_error_count"],
                    "console_errors_sample": row["console_errors"],
                })
                if row["truth"]:
                    entry["ground_truth_window___truth"] = row["truth"]
            manifest["pages"][name] = entry
        index: dict[str, list[str]] = {}
        for name, (_what, mines) in PAGES.items():
            for mine in mines:
                index.setdefault(mine, []).append(name)
        manifest["landmine_index"] = {k: index[k] for k in sorted(index)}
        (HERE / "MANIFEST.json").write_text(
            json.dumps(manifest, indent=1, sort_keys=True), encoding="utf-8")
        print(f"\nwrote {HERE / 'MANIFEST.json'}")

    if failed:
        print(f"\nFAILED: {failed}")
        sys.exit(1)
    print(f"\nall {len(rows)} pages loaded, no page errors")


if __name__ == "__main__":
    asyncio.run(main())
